"""Initial migration with ULIDs

Revision ID: 10dfe46315c7
Revises: 
Create Date: 2025-10-22 14:22:09.384785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10dfe46315c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_locations_uid'), 'locations', ['uid'], unique=True)
    op.create_table('services',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('technician_operation_duration', sa.Integer(), nullable=True, comment='in minutes'),
    sa.Column('room_operation_duration', sa.Integer(), nullable=True, comment='in minutes'),
    sa.Column('buffer_time', sa.Integer(), nullable=True, comment='in minutes'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_services_uid'), 'services', ['uid'], unique=True)
    op.create_table('users',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('role', sa.Enum('customer', 'technician', 'admin', name='user_role_enum'), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('appointments',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('customer_id', sa.String(length=26), nullable=True),
    sa.Column('service_id', sa.String(length=26), nullable=True),
    sa.Column('location_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'completed', 'cancelled', name='appointment_status_enum'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.uid'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_appointments_uid'), 'appointments', ['uid'], unique=True)
    op.create_table('resources',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('technician', 'room', name='resource_type_enum'), nullable=False),
    sa.Column('location_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_resources_uid'), 'resources', ['uid'], unique=True)
    op.create_table('technician_service_link',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('service_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'service_id')
    )
    op.create_table('appointment_resource_links',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('appointment_id', sa.String(length=26), nullable=True),
    sa.Column('resource_id', sa.String(length=26), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.uid'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_appointment_resource_links_uid'), 'appointment_resource_links', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_resource_links_uid'), table_name='appointment_resource_links')
    op.drop_table('appointment_resource_links')
    op.drop_table('technician_service_link')
    op.drop_index(op.f('ix_resources_uid'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_appointments_uid'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_uid'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_locations_uid'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
