"""Make user nickname and phone nullable

Revision ID: 99c6fa7d57cc
Revises: 10dfe46315c7
Create Date: 2025-10-22 15:06:20.441134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99c6fa7d57cc'
down_revision: Union[str, Sequence[str], None] = '10dfe46315c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               nullable=False)
    # ### end Alembic commands ###
