"""Create social_accounts table for multi-provider auth

Revision ID: c62fdbda15e6
Revises: 99c6fa7d57cc
Create Date: 2025-10-22 15:22:33.022310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62fdbda15e6'
down_revision: Union[str, Sequence[str], None] = '99c6fa7d57cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='e.g., wechat, xiaohongshu'),
    sa.Column('provider_id', sa.String(length=128), nullable=False, comment='OpenID, XHS OpenID, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_provider_provider_id')
    )
    op.create_index(op.f('ix_social_accounts_provider'), 'social_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_social_accounts_provider_id'), 'social_accounts', ['provider_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_uid'), 'social_accounts', ['uid'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_uid'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_provider_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_provider'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
