"""V6 Arch: Add Shift table for technician scheduling

Revision ID: cb030248aed2
Revises: f6528ee22667
Create Date: 2025-10-23 15:13:48.556251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb030248aed2'
down_revision: Union[str, Sequence[str], None] = 'f6528ee22667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('technician_id', sa.String(length=26), nullable=False),
    sa.Column('location_id', sa.String(length=26), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='排班开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='排班结束时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.uid'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_shifts_location_id'), 'shifts', ['location_id'], unique=False)
    op.create_index(op.f('ix_shifts_technician_id'), 'shifts', ['technician_id'], unique=False)
    op.create_index(op.f('ix_shifts_uid'), 'shifts', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_uid'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_technician_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_location_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
