"""V4 Arch: Separate technician and resource booking

Revision ID: f6528ee22667
Revises: c62fdbda15e6
Create Date: 2025-10-23 14:57:27.624223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6528ee22667'
down_revision: Union[str, Sequence[str], None] = 'c62fdbda15e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_technician_links',
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('appointment_id', sa.String(length=26), nullable=False),
    sa.Column('technician_id', sa.String(length=26), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.uid'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_appointment_technician_links_uid'), 'appointment_technician_links', ['uid'], unique=False)
    op.alter_column('appointment_resource_links', 'appointment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=False)
    op.alter_column('appointment_resource_links', 'resource_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=False)
    op.drop_index(op.f('ix_appointment_resource_links_uid'), table_name='appointment_resource_links')
    op.create_index(op.f('ix_appointment_resource_links_uid'), 'appointment_resource_links', ['uid'], unique=False)
    op.alter_column('appointments', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=False)
    op.alter_column('appointments', 'service_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=False)
    op.alter_column('appointments', 'location_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('confirmed', 'completed', 'cancelled', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_appointments_uid'), table_name='appointments')
    op.create_index(op.f('ix_appointments_uid'), 'appointments', ['uid'], unique=False)
    op.drop_index(op.f('ix_locations_uid'), table_name='locations')
    op.create_index(op.f('ix_locations_uid'), 'locations', ['uid'], unique=False)
    op.alter_column('resources', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='例如: 1号推拿床, 2号针灸室',
               existing_nullable=False)
    op.alter_column('resources', 'location_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=False)
    op.drop_index(op.f('ix_resources_uid'), table_name='resources')
    op.create_index(op.f('ix_resources_uid'), 'resources', ['uid'], unique=False)
    op.drop_column('resources', 'type')
    op.alter_column('services', 'technician_operation_duration',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='in minutes')
    op.alter_column('services', 'room_operation_duration',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='in minutes')
    op.alter_column('services', 'buffer_time',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='in minutes')
    op.drop_index(op.f('ix_services_uid'), table_name='services')
    op.create_index(op.f('ix_services_uid'), 'services', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_uid'), table_name='services')
    op.create_index(op.f('ix_services_uid'), 'services', ['uid'], unique=True)
    op.alter_column('services', 'buffer_time',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='in minutes')
    op.alter_column('services', 'room_operation_duration',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='in minutes')
    op.alter_column('services', 'technician_operation_duration',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='in minutes')
    op.add_column('resources', sa.Column('type', mysql.ENUM('technician', 'room', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_index(op.f('ix_resources_uid'), table_name='resources')
    op.create_index(op.f('ix_resources_uid'), 'resources', ['uid'], unique=True)
    op.alter_column('resources', 'location_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=True)
    op.alter_column('resources', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='例如: 1号推拿床, 2号针灸室',
               existing_nullable=False)
    op.drop_index(op.f('ix_locations_uid'), table_name='locations')
    op.create_index(op.f('ix_locations_uid'), 'locations', ['uid'], unique=True)
    op.drop_index(op.f('ix_appointments_uid'), table_name='appointments')
    op.create_index(op.f('ix_appointments_uid'), 'appointments', ['uid'], unique=True)
    op.alter_column('appointments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('confirmed', 'completed', 'cancelled', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('appointments', 'location_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=True)
    op.alter_column('appointments', 'service_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=True)
    op.alter_column('appointments', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=True)
    op.drop_index(op.f('ix_appointment_resource_links_uid'), table_name='appointment_resource_links')
    op.create_index(op.f('ix_appointment_resource_links_uid'), 'appointment_resource_links', ['uid'], unique=True)
    op.alter_column('appointment_resource_links', 'resource_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=True)
    op.alter_column('appointment_resource_links', 'appointment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26),
               nullable=True)
    op.drop_index(op.f('ix_appointment_technician_links_uid'), table_name='appointment_technician_links')
    op.drop_table('appointment_technician_links')
    # ### end Alembic commands ###
